### ISSUE TITLE
Unable to run the basic ECMWF example

### ISSUE THREAD

**Issue by winash12** [ecmwf/metview-python#12]
I am trying to run this example https://confluence.ecmwf.int/display/METV/2m%20Temperature%20Plot%20Example

and I am getting this error. I have the latest version of metview and the latest version of the python bindings. Any ideas where I am going wrong ? Looking at the python bindings it does not appear that there is a pdf_output. 

```
Traceback (most recent call last):
File "plot_t2m.py", line 21, in <module>
mv.setoutput(mv.pdf_output(output_name = 'plot_t2m'))
AttributeError: module 'metview' has no attribute 'pdf_output'
```

**Comment by iainrussell** [comment]
Hi @winash12 ,

What if you put ps_output instead of pdf_output - what happens then?

Iain

**Comment by winash12** [comment]
@iainrussell Wow that was quick.

Here is the output - 
```
Traceback (most recent call last):
  File "/home/winash12/metview/System/Templates/General/Python Script.py", line 10, in <module>
    mv.setoutput(mv.ps_output(output_name = 'plot_t2m'))
AttributeError: module 'metview' has no attribute 'ps_output'
```

**Comment by winash12** [comment]
@iainrussell So in cooperation with Xavier Abellan(JIRA) we have identified the problem. Hopefully you can give me a fix.

In Metview-5.3.0 the installation of uPlotManager is in the wrong directory

It goes /usr/loca/bin/metview_bin and not under /usr/local/bin/metview_bin/uPlotManager.

So I was unable to even visualize it using metview.

**Comment by winash12** [comment]
@iainrussell Problem resolved. It was an error that I made during installation.

**Comment by iainrussell** [comment]
@winash12 , glad you managed to get it resolved, and hope you enjoy using Metview!
