### ISSUE TITLE
bad installation through conda 

### ISSUE THREAD

**Issue by jhbravo** [ecmwf/metview-python#14]
I install metview using conda like [tutorial page](https://confluence.ecmwf.int/display/METV/Metview%27s+Python+Interface) the metview interface works fine, but I can't call from python `import metview as mv`
![screenshot_20200121_ 153711](https://user-images.githubusercontent.com/18407824/72845579-87258280-3c64-11ea-9d4f-974b9fe193c8.png)
I try whit environment variables
`import os`
`os.environ["METVIEW_PYTHON_DEBUG"] = "1"`
`os.environ["METVIEW_PYTHON_START_CMD"] = "/home/jhbravo/Software/miniconda3/envs/metview/bin/metview"`
`import metview as mv`
but it doesn't work either

same situation with Magics.macro. I think Magics did not install, when I installing metview

**Comment by iainrussell** [comment]
Hi @jhbravo , to get the Python interface, you need to install it separately:
`pip install metview`
We do plan to make it part of the conda installation, but it's not there yet.
I hope this helps!
Iain

**Comment by jhbravo** [comment]
Hello @iainrussell  and thanks for your quick response
I see the problem, I thought the python interface is installed by default

> maybe someone need this for starts with metview, 
> do I install metview through conda
> 1.- `conda install -c conda-forge metview`
> 2.- `git clone https://github.com/ecmwf/metview-python.git`
> 3.- copy the metview folder in the site-packages
> `cp metview-python/metview /home/main/miniconda3/envs/metview/lib/python3.8/site-packages`
> 4.- due to the variables are not set, you still can't call metview-python interface, the variables can be set in python, 
> 5.- `import os, sys`
> `os.environ["METVIEW_PYTHON_START_CMD"] = "/home/main/miniconda3/envs/metview/bin/metview"`
> `sys.path.append("/home/main/miniconda3/envs/metview/lib/python3.8/site-packages")`
> 6.- finally you can call metview-python interface, I use spyder and it works fine in the first test
> `import metview as mv`
>

**Comment by iainrussell** [comment]
Hi @jhbravo, it should be enough to do
`pip install metview` within your conda environment. If you're in the conda environment then the python interface will be able to connect to Metview.
