### ISSUE TITLE
pip install metview 

### ISSUE THREAD

**Issue by HamidPahlavan** [ecmwf/metview-python#16]
"pip install metview" installs an old version of metview (i.e. 1.5.1) instead of the latest one.

**Comment by iainrussell** [comment]
Hi @HamidPahlavan , well spotted!  But..... Metview comes in 2 parts - the binaries (based on C++ code and available through conda `conda install metview -c conda-forge`), which gives you 5.9.1; and the Python bindings, which follow a different release cycle, as they are not tied to particular versions of the binaries. The latest Python bindings should always work with the latest binaries, but also (in general) with older versions. So the current version of the Python bindings is 1.5.1, which is what's available on pip, so I believe everything is correct!

I hope that answers your concern, thanks for taking the time to point it out though

**Comment by krishnaap** [comment]
After installing via pip, how can I run MetView GUI?

**Comment by iainrussell** [comment]
Hi @krishnaap , check out my response above - you need to install the binaries through conda, then type 'metview' from a shell in your conda environment.
Cheers,
Iain
