### ISSUE TITLE
 Execute Python scripts with left click

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#17]
![image](https://user-images.githubusercontent.com/64424891/98461976-9b614e80-21a8-11eb-9fda-50c051627d27.png)

Is it possible to save commands in icons that run Python scripts or macros with a double click, much like the Shell Script Icon, but without requiring from user to open it with the editor and run it ( F9 ) ?
So that the user will open the grib file of each folder with one click of the command icon and will have many products ready, easy and fast, even if the grib files are replaced by newer ones.

It would be much better if commands for products could saved in user interface toolbar

![image](https://user-images.githubusercontent.com/64424891/98462263-db293580-21aa-11eb-972e-858d050bac8c.png)

**Comment by iainrussell** [comment]
Hi, if I understand your question correctly, if you have Macro or Python scripts, you can right-click on those icons and select 'execute' to run them. If this sounds like what you want to do, let me know if you need help creating Macro or Python icon. Cheers!

**Comment by gkafk** [comment]
Hi,
thank you for your quick reply.

Now it works  with right click, opens the editor and starts the process. But this is not what I want.
I would like to run scripts just with  double or simple left click. 
Is it possible?

**Comment by iainrussell** [comment]
Hi, the quickest way possible is to right-click/execute. Double-click is assigned to 'edit' and cannot be customised. Do you at least see the 'execute' item in the context menu when you right-click?
![image](https://user-images.githubusercontent.com/40060766/98524730-7b489280-226f-11eb-9f81-a8248f78b43c.png)

**Comment by gkafk** [comment]
Yes, I see it and works fine in this way.
If I could assign double-click to 'Execute' would be nice.
