### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGUSR1'

### ISSUE THREAD

**Issue by liseeocean** [ecmwf/metview-python#20]
Hi developer, I try to pip install metview within anaconda prompt in the win10 environment but failed. Errors are as follows when I python -m metview selfcheck :
Trying to connect to a Metview installation...
Could not find a valid Metview installation
...
    signal.signal(signal.SIGUSR1, self.signal_from_metview)
AttributeError: module 'signal' has no attribute 'SIGUSR1'.

**Comment by iainrussell** [comment]
Hi @liseeocean,
I'm afraid that Metview's Python API requires an installation of Metview itself, which is not supported on Windows. On MacOS or Linux, you can install Metview via conda, e.g. `conda install metview -c conda-forge`  followed by `pip install metview`.

Best regards,
Iain
