### ISSUE TITLE
Open Geography tool with python and get line coords

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#22]
Hi Iain,

is it possible to open **Geography Tool** through python code, 
after that draw a line by hand and get the line coordinates for producing a cross section plot?
Also  can I put grib and contours in Geography tool with python like this image?

![image](https://user-images.githubusercontent.com/64424891/111883756-f2342b80-89c5-11eb-8f11-100a9055f57f.png)

Thank you
George

**Comment by iainrussell** [comment]
Hi George,

Interesting question - no, it's not possible to open the Geography Tool from Python, but it's a good idea! Not straightforward to do, but I'll add it to our internal list of issues to look at in the future. And this answers your second question as well of course, it's not possible to do that from Python. If, however, you have a Macro script that returns data/and/or/contours then you can drop that into the Geography Tool window.

Cheers,
Iain

**Comment by gkafk** [comment]
Hi Iain,

thank you for your immediate answer!
I am looking forward to!

George

**Comment by iainrussell** [comment]
I've entered it into our 'wishlist', so I'll close this issue. Thanks again for your interest in Metview!
