### ISSUE TITLE
Python - merge datasets

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#23]
Hi Iain,

I saw in documentation that I can **merge multiple fieldsets** at once in macro, if I am right.

[https://confluence.ecmwf.int/display/METV/Fieldset+Functions](url)

`fieldset merge ( fieldset,fieldset,... )`

_Merge several fieldsets. The output is a fieldset with as many fields as the total number of fields in all merged fieldsets. Merging with the value nil does nothing, and is used to initialise when building a fieldset from nothing._

**Is it possible to do it in python?** 
I have not succeeded in it yet, but it works by using merge for 2 fieldsets each time in a loop.

like that:
[https://github.com/ecmwf/metview-python/blob/master/tests/test_metview.py](url)
`   g3 = mv.merge(grib[1], grib[0])`

Thank you
George

**Comment by iainrussell** [comment]
Hi George,

I don't have a dev environment on this machine, but it should indeed be possible to do this:
`fs_merged = mv.merge(f1, f2, f3, f4)`
or alternatively you can do this:
`fs_merged = mv.Fieldset(fields==[f1, f2, f3, f4])`
To start with nothing, you can do this (untested code):
```
fs_merged = mv.Fieldset()
fs_merged.append(f1)
fs_merged = mv.merge(fs_merged, f2, f3)
```

If you check out the tests in test_metview.py from line 744 to line 816 you'll see various ways of doing it.

I hope this helps!
Iain

**Comment by gkafk** [comment]
This did not work to me:
`fs_merged = mv.merge(f1, f2, f3, f4)`

neither this:
`fs_merged = mv.Fieldset(fields=[f1, f2, f3, f4])`

this worked:
`fs_merged = mv.Fieldset()`
`fs_merged.append(f1)`

but sometimes throws **NonType object has no attribute  val pointer**

and maybe always
**python - ERROR - compute function merge needs at least 2 arguments**
where I am giving the **fs_merged** list to merge.

cases that I do not have when I am using loop and merge by two fieldsets.

**Comment by iainrussell** [comment]
Hi, only since metview-python 1.7.0 does the merge function accept a single
argument, so you may be using an old version.

**Comment by gkafk** [comment]
You are right, I had 1.4.0 and I updated it to 1.7.0.

But still I cannot do` fs_merged = mv.Fieldset(fields=[f1, f2, f3, f4]).`

I am ok with appending fieldsets. 
`fs_merged.append(f1)`

Thank you
