### ISSUE TITLE
Plotting grid point values over land

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#24]
hi Iain,

Is there any option in contours when plotting grid point values, like 2 metre temperature, 
to plot only the values over land?
Not by overlapping with map over sea values...

Thank you
George

![image](https://user-images.githubusercontent.com/64424891/115192226-0dd04600-a0da-11eb-9d10-c92d54f1cc7c.png)

**Comment by iainrussell** [comment]
Hi George,

Your two options for doing this kind of thing are:
1) graphical - e.g. https://confluence.ecmwf.int/display/METV/Contour%20Shading%20Only%20Over%20Land%20Example but this would wipe out everything that is over the sea
2) data - you will need GRIB data that is a land-sea mask and use it with the bitmap() function to remove the data points over the sea before you plot it. See this example: https://confluence.ecmwf.int/display/METV/Model%20Orography%20with%20Land%20Sea%20Mask%20Example

I hope that helps!
Iain

**Comment by gkafk** [comment]
Cannot bitmap t2m and lsm.
bitmap need the same number of grid points
![image](https://user-images.githubusercontent.com/64424891/116527307-10951d00-a8ca-11eb-88ef-b3c68f19bcd5.png)

Any solution?

**Comment by iainrussell** [comment]
Hi George,
I just updated an FAQ on this recently - an example of doing this exact thing is here:
https://confluence.ecmwf.int/pages/viewpage.action?pageId=143038050

Cheers,
Iain

**Comment by gkafk** [comment]
Hi Iain,

I saw that and I have done it by giving the same area in read() function on both grib files ( lsm and t2m ).
![image](https://user-images.githubusercontent.com/64424891/116539030-d599e600-a8d7-11eb-9bce-b76c43117d04.png)

I was trying to find a function that gets the data area from first  fieldset and apply it to the second fieldset.
Also I can not find functions documentation, in a way that I can find icons reference, 
e.g cannot find  read() function arguments, like magics mcont 
https://confluence.ecmwf.int/display/MAGP/Contouring
which is very nice, and could be better in my opinion.

Thank you for your help Iain.
George

**Comment by iainrussell** [comment]
Hi George,

We're close to publishing complete documentation for Metview's Python interface on readthedocs, which we expect to publish in the next 10 days or so. This should make it much easier to find what you're looking for, as the documentation has been restructured and functions such as read() are fully documented.

Cheers,
Iain

**Comment by gkafk** [comment]
Nice! 

Thanks Iain
