### ISSUE TITLE
different text sizes

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#27]
Hi,

When I use  **text font size = 0.7**  in mv.mtext  while producing png images in 1800 width

![image](https://user-images.githubusercontent.com/64424891/120631306-43957800-c457-11eb-8e43-7bcfcc1ba0f1.png)

I have this size of text

![image](https://user-images.githubusercontent.com/64424891/120631471-73448000-c457-11eb-8ee8-6b09b611f2e6.png)

but with 0.7 size in uplot I have this enormous size of text

![image](https://user-images.githubusercontent.com/64424891/120631773-c4ed0a80-c457-11eb-8981-08cadf11af12.png)

How can adjust it to have the same size in all type of views?
is there any way to specify dimensions for  uplot image?

Thank you 
George

**Comment by iainrussell** [comment]
Hi George,

We've lived with inconsistencies in font sizes for a long time, and it's not so trivial to make it work nicely automatically.

However, if you use Metview 5.12.0 (i.e. the latest version) underneath the Python bindings, you will have access to a new parameter in png_output() and pdf_output(), so you can do something like:
`mv.setoutput(mv.png_output(output_font_scale=2.0, ....))`
This will scale all the fonts used in the PNG output by that amount (default is 1.0, i.e. no change). This gives a one-line way to make all the fonts a better size. I hope it's useful to you!

https://confluence.ecmwf.int/display/METV/Version+5.12+Updates

Cheers,
Iain

**Comment by gkafk** [comment]
Thanks Iain!!

It works nice!

**Comment by iainrussell** [comment]
Great, thanks for letting me know!
Iain
