### ISSUE TITLE
Using Text for the same grib

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#31]
Hi Iain,

I am constructing a map using a grib file name more than 2 times ( alone and in formula ).
**Each grib contains a lot of steps.**
So in title it is apperaring at least duplicated. 
I need showing step, start time and valid time for every frame.

![image](https://user-images.githubusercontent.com/64424891/133370651-072792d4-db28-4941-9725-9b27593cf698.png)

In this case, using filtered title is not helpful, because in **where='shortName=gh'**   I have the same results, as expected.
Is there any way of reducing it down? Not showing duplicated?
Or at least reducing valid time lines to one?

![image](https://user-images.githubusercontent.com/64424891/133371149-be5c7c1d-9ffa-44e8-af60-b7474c3b7538.png)

![image](https://user-images.githubusercontent.com/64424891/133372701-c0e3d0df-69b8-42c3-a671-bfcc2ebec91d.png)

Ideal condition to use  step, start time and valid time pointing to specific grib file.

thanks 
George

**Comment by iainrussell** [comment]
Hi George,

This can be a little tricky, but perhaps in your case you can do something sneaky such as changing the parameter identifier of all-but-one of your fields. Here's a small example I wrote for myself:

```
import metview as mv

a = mv.read('my_data.grib')
b = a+17
b = mv.grib_set_long(b, ['paramId', 79])

t = "<grib_info key='shortName' where='shortName=t'/> <grib_info key='level' where='shortName=t'/>"
title = mv.mtext(text_line_1=t)

mv.plot(a, b, title)
```
The choice of 79 for the paramId is arbitrary, just make sure it is not the same as the paramId of the original data! I think the only potential trap here is if the new parameter has a different scaling factor applied to it when plotting! You can deactivate this scaling by setting grib_scaling_of_derived_fields='off' in the mcont() definition.

I hope this helps!
Cheers,
Iain

**Comment by gkafk** [comment]
Thanks Iain.
It works.

**Comment by iainrussell** [comment]
Thanks for letting me know, George.
