### ISSUE TITLE
contour_grid_value_justification

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#32]
Hi Iain,

I am trying to plot winds on points showing direction and speed number.

![image](https://user-images.githubusercontent.com/64424891/134012740-a088e73f-b171-4cb1-9f25-0bf5bc355a34.png)

The problem as you can see in the image, is  that I can not adjust the position of wind  labels and they appeared in the same point.
I tryied **contour_grid_value_justification** from magics  Reference guide,   but it didn't work.
[https://confluence.ecmwf.int/display/MAGP/Contouring](url)

**This is one of my contours.**
opera_w_850 = mv.mcont(
       contour                                      = "off",
       contour_level_selection_type     = "interval",
       contour_interval                         = 1.0,
       contour_label_blanking              = "off",
       contour_label_frequency            = 1,
       contour_grid_value_plot              = "on",
       contour_grid_value_lat_frequency = 3,
       contour_grid_value_lon_frequency = 3,
       contour_grid_value_height        = 0.3,
       contour_grid_value_colour        = "blue",
       contour_grid_value_plot_type     = "both",  _(tried value and marker)_
       contour_grid_value_position      = "left",
       #contour_grid_value_justification = "left",   
       #contour_grid_value_vertical_align= "base" 
      )

It returns an error as like metview does not include all magics parameters.
![image](https://user-images.githubusercontent.com/64424891/134020492-e08428f6-11de-4f97-a6ea-38358fc5dce7.png)

Thank you 
George

**Comment by iainrussell** [comment]
Hi George,
Thanks for pointing this out, I was not aware that these parameters existed in Magics! I have now added them to Metview and they seem to work nicely (note that 'position' works only if both markers and values are plotted, and 'justification' and 'align' work only if only the values are plotted).

Now, you probably don't want to wait for the next Metview release (which will probably be around November), so there is a way that you can already try these new parameters, if you don't mind 'hacking' your Metview installation a bit!

To do this, find where Metview is installed on your system, and there should be a subdirectory called 'share/metview/etc'. Inside that directory will be lots of files, two of them are called MCONTDef and MCONTRules. Make a backup of these files, then copy the versions of those files attached to this message there. Then restart your session (just kill the Python kernel and restart your script), and you should have the new parameters available to you!
[MCONT.zip](https://github.com/ecmwf/metview-python/files/7197407/MCONT.zip)

If all of that still does not allow you to get the plot you want, we can also play with converting the GRIB data to Geopoints format, which will allow you to shift the positions.

Good luck!
Iain

**Comment by gkafk** [comment]
Thanks Iain.
It worked. I had to change files in 2 different folders.

![image](https://user-images.githubusercontent.com/64424891/134055910-7d26b96f-ceb2-4424-9ef4-29145a657eef.png)

**Comment by iainrussell** [comment]
Excellent - thanks for letting me know!
