### ISSUE TITLE
mtext title problem (cannot disappear  the title)

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#33]
Hi Iain,

![image](https://user-images.githubusercontent.com/64424891/136770992-5f0faa60-aa8c-45d4-b378-aa7c120bc9cc.png)

When I use` text_mode = 'title'`  , I get the right title on the default place, without **magics_title**

![image](https://user-images.githubusercontent.com/64424891/136771245-100e2deb-9619-453f-9434-28fa758aabea.png)

but when I use `text_mode = 'positional' ` , I get the text I need , in place I want, but I get title again.

![image](https://user-images.githubusercontent.com/64424891/136772186-3f0342c9-3c20-4f7c-ac5b-6fd97df93ef1.png)

How can I  disappear the title when I m working with positional text?

**Comment by iainrussell** [comment]
Hi George,

Thankfully I wrote a FAQ on this a while ago - hopefully this will sort you out.

https://confluence.ecmwf.int/display/UDOC/How+to+replace+the+default+title+with+a+positional+one+-+Metview+FAQ

Best regards,
Iain

**Comment by iainrussell** [comment]
Great, thanks for letting me know!
Iain
