### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by legibe** [ecmwf/metview-python#36]
Dialog (that works in Macro) does not seem to be exposed in the Python API, while slider is. Is that an oversight?
I would like to be able to create dialogs in Metview from Python.
Thanks.

**Comment by sandorkertesz** [comment]
Hi Claude, 

Thank you for reporting it. It has now been fixed and will be available in the next release (most probably 1.9.0). 

Many thanks,
Sandor

**Comment by sandorkertesz** [comment]
Hi Claude, 1.9.0 has been released and is available on pypi/conda-forge.
