### ISSUE TITLE
How to use metview-python in a Google Colab Notebook ?

### ISSUE THREAD

**Issue by jpmacveigh** [ecmwf/metview-python#42]
!pip install metview
import metview as mv

gives :
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting metview
  Downloading metview-1.12.0-py2.py3-none-any.whl (392 kB)
     |████████████████████████████████| 392 kB 4.9 MB/s 
Requirement already satisfied: cffi in /usr/local/lib/python3.7/dist-packages (from metview) (1.15.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from metview) (1.3.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from metview) (2.23.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from metview) (3.13)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from metview) (1.21.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi->metview) (2.21)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->metview) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->metview) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->metview) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->metview) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->metview) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->metview) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->metview) (3.0.4)
Installing collected packages: metview
Successfully installed metview-1.12.0
Could not run the Metview executable ('metview'); check that the binaries for Metview (version 5 at least) are installed and are in the PATH.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-1-127c8792bbf7>](https://localhost:8080/#) in <module>()
      1 get_ipython().system('pip install metview')
----> 2 import metview as mv

6 frames
[/usr/lib/python3.7/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1549                         if errno_num == errno.ENOENT:
   1550                             err_msg += ': ' + repr(err_filename)
-> 1551                     raise child_exception_type(errno_num, err_msg, err_filename)
   1552                 raise child_exception_type(err_msg)
   1553 

FileNotFoundError: [Errno 2] No such file or directory: 'metview': 'metview'

**Comment by sandorkertesz** [comment]
Hello,
Metview Python requires the Metview binaries to be installed. This can be done either from source or via conda, but not through pip. That is why you get the following message:

Could not run the Metview executable ('metview'); check that the binaries for Metview (version 5 at least) are installed and are in the PATH.

**Comment by iainrussell** [comment]
Thanks @jpmacveigh for sharing that formula with us (and the community)!
