### ISSUE TITLE
Can't install binaries on ubuntu 22.04

### ISSUE THREAD

**Issue by rochutb** [ecmwf/metview-python#45]
Hello, 

I'm facing some difficulties to install metview on my VPS on ubuntu 22.04
I installed the python package but the command : 
conda install -c conda-forge metview is not working (time out) 

It's maybe a problem with the new version of Ubuntu ? 

Thanks a lot 
Basile

**Comment by iainrussell** [comment]
Hello @rochutb,

It could be some kind of network issue (proxies?) that is preventing you from connecting to the conda-forge package servers. Try installing something 'basic' like curl. If that does not work, then you may need to do some digging...

Best regards,
Iain

**Comment by rochutb** [comment]
> Hello @rochutb,
> 
> It could be some kind of network issue (proxies?) that is preventing you from connecting to the conda-forge package servers. Try installing something 'basic' like curl. If that does not work, then you may need to do some digging...
> 
> Best regards, Iain

Hello @iainrussell, thanks for your answer, it finally worked. It was a slow network connection with conda-forge I don't know why but the problem wasn't from met view ! 

Thanks again, 
Best regards,
Basile
