### ISSUE TITLE
tag 1.15.0 missing ?

### ISSUE THREAD

**Issue by thebaptiste** [ecmwf/metview-python#53]
### What happened?

A release 1.15.0 is available on pypi, but there is no 1.15.0 tag on github. It's surprising...

### What are the steps to reproduce the bug?

Nothing to add

### Version

1.15.0

### Platform (OS and architecture)

rockylinux

### Organisation

Meteo-France

**Comment by iainrussell** [comment]
Thanks, it was an oversight due to working with multiple repo origins - fixed now!
