### ISSUE TITLE
Regrid fails saying "service died before completing the request"

### ISSUE THREAD

**Issue by deepgabani8** [ecmwf/metview-python#56]
### What happened?

This is with regards to a previous issue: https://github.com/ecmwf/metview-python/issues/50

Using the interpolation method other than the default - 'linear' worked earlier but now it gives the error. When trying to regrid the grib data, it gives the error saying

```
Exception: Metview error: Service regrid@860306 died before completing the request
```

### What are the steps to reproduce the bug?

 https://github.com/deepgabani8/temp/blob/master/grib-with-metview-error/201201010000_FH-0.gb is a grib file from the dataset which I am working on. It is in reduced gaussian grid and I need to regrid it to [0.1, 0.1]. While doing `mv.regrid`, it fails.

### Version

v1.13.1

### Platform (OS and architecture)

Linux gabani.c.googlers.com 6.5.13-1rodete2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete2 (2024-01-11) x86_64 GNU/Linux

### Organisation

google/weather-tools

**Comment by deepgabani8** [comment]
@iainrussell

**Comment by deepgabani8** [comment]
My bad. I tried this on a fresh environment and it worked with interpolation method.

**Comment by iainrussell** [comment]
Hi @deepgabani8,

Aha, I was just responding to say that it worked for me! Glad you managed to solve it.

Best regards,
Iain
