### ISSUE TITLE
rpc moved to tirpc/rpc in Fedora 29

### ISSUE THREAD

**Issue by sankayop** [ecmwf/metview-python#6]
Hi,
I'm using Fedora 29 (4.19.4-300.fc29.x86_64)

I struggled a bit during the installation of MetviewBundle-2018.10.0-Source but finally succeed to get it working.

Perhaps, I did something wrong but if not, the solution is below.

What I had to change and where:
- build/mars-client/src/rpcmars.h
- build/mars-client/src/marsxdr.c
each time, there was an #include <rpc/...>, I had to replace it by  #include <tirpc/rpc/...> because when installing libtirpc and rpcgen, it occured libtirpc was installed in /usr/include/tirpc/rpc and not /usr/include/rpc

Moreover, I also had to do the same for all files inside /usr/include/tirpc/rpc/

This is not a Metview bug but might be interesting for your Fedora users.
reference: https://github.com/ArcticaProject/nx-libs/issues/665

**Comment by iainrussell** [comment]
Hi sankayop,

Many thanks for this information. In fact, we became aware of it a while ago and have already incorporated a fix; however, this does not apply to the bundle, only to the 'standalone' Metview source. We have a better fix in a branch, which should solve this problem in an upcoming release.

Cheers,
Iain
